# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.kernelPackages = pkgs.linuxPackages;
  boot.kernelParams = [
    "amdgpu.runpm=0"
    "amdgpu.dcdebugmask=0x8"
    "amdgpu.sg_display=0"
  ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/6f8ccdda-c92a-447b-bcdf-3e88e6e3c4ae";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/0144-855F";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/mnt/storage" =
    { device = "/dev/disk/by-uuid/5A6C-926F";
      fsType = "exfat";
      options = [ "uid=1000" "gid=100" "dmask=022" "fmask=133" ];
    };

  swapDevices = [
    { device = "/var/lib/swapfile"; size = 16 * 1024; }  # 16GB swapfile
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.enableAllFirmware = true;
  hardware.enableRedistributableFirmware = true;
  hardware.cpu.amd.updateMicrocode = true;
}

